### ISSUE TITLE
TypeError: Cannot read property 'Xp' of undefined

### ISSUE THREAD

**Issue by caleb718** [Asgarrrrr/Luna#4]
TypeError: Cannot read property 'Xp' of undefined
    at Client.client.on (....Luna.js:166:23)

Happens when attempting to input a command. 
Ex. $ping

**Comment by Asgarrrrr** [comment]
Thank you for your feedback !

This problem is encountered when sending a message, indeed if you are not registered in the database, it is not possible to add an amount of experience to your profile, this will be corrected in the next version 😕
